### ISSUE TITLE
was macht das denn/what makes it then

### ISSUE THREAD

**Issue by PSeitz** [verfehlix/huehuehue#1]

**Comment by verfehlix** [comment]
It seems like you have not starred this repository yet.
To get an answers to your question, please starr this repository and then comment here with:

```
//////////////////////////////////////////////////////////////
.___  .__                        
|   | |  |__ _____ ___  __ ____  
|   | |  |  \\__  \\  \/ // __ \ 
|   | |   Y  \/ __ \\   /\  ___/ 
|___| |___|  (____  /\_/  \___  >
           \/     \/          \/ 
          __                                  .___
  _______/  |______ ______________   ____   __| _/
 /  ___/\   __\__  \\_  __ \_  __ \_/ __ \ / __ | 
 \___ \  |  |  / __ \|  | \/|  | \/\  ___// /_/ | 
/____  > |__| (____  /__|   |__|    \___  >____ | 
     \/            \/                   \/     \/ 
///////////////////////////////////////////////////////////////
```

Thanks!

**Comment by PSeitz** [comment]
Okay I starred at the project
//////////////////////////////////////////////////////////////
.___  .__  
|   | |  |__ _____ ___  __ ____  
|   | |  |  \__  \  \/ // __ \ 
|   | |   Y  \/ __ \   /\  **_/ 
|**_| |**_|  (_**_  /_/  ___  >
           \/     \/          \/ 
          __                                  .___
  _______/  |______ ______________   ____   **| _/
 /  ___/\   __\**  \_  __ _  __ _/ __ \ / __ | 
 ___ \  |  |  / __ |  | \/|  | \/\  **_// /_/ | 
/__**  > |**| (__**  /**|   |**|    ___  >____ | 
     \/            \/                   \/     \/ 
///////////////////////////////////////////////////////////////

**Comment by verfehlix** [comment]
Thanks for starring at our project!
You'll soon recieve a call concerning your question!
Have I answered all your customer concerns in a timely and satisfactory fashion today?

**Comment by PSeitz** [comment]
Yes, thank you. Almost all questions have been answered
